http:
  port:8081
  
  

   
jlogger:
   applicationName:okta-authentication-sapi
   applicationVersion:1.0
   environment:dev
   
httprequest:
    basepath:/api/v1
    protocol:HTTPS
    host:dev-25511193.okta.com
    port:443
       